version: '3.8'
# just a test for checking ci/cd pipeline
services:

  gateway:
    build: ./gateway
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - ./backend/.env
    stdin_open: true
    tty: true

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: